version: '3.9'

services:

    # Nginx Service
    #    webserver:
    #        container_name: '${PROJECT_ALIAS}_nginx'
    #        image: nginx:alpine
    #        restart: unless-stopped
    #        tty: true
    #        ports:
    #            - "80:80"
    #            - "443:443"
    #        volumes:
    #            - ./laravel:/var/www/html
    #            - ./laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf

    # Laravel app
    #    app:
    #        container_name: '${PROJECT_ALIAS}_app'
    #        build:
    #            context: .
    #            dockerfile: ./Dockerfile
    #        restart: unless-stopped
    #        volumes:
    #            - ./:/var/www/html
    #        working_dir: /var/www/html
    #        ports:
    #            - "9012:9000"
    #        command: bash -c "composer install && composer init && npm run build && php artisan key:generate && php artisan migrate && php artisan serve"
    #        environment:
    #            DB_CONNECTION: mysql
    #            DB_HOST: db
    #            DB_PORT: 3306
    #            DB_DATABASE: laravel
    #            DB_USERNAME: user
    #            DB_PASSWORD: secret
    #        depends_on:
    #            - mysql

#    laravel_app:
#        restart: unless-stopped
#        build:
#            context: .
#            target: php_base
#        volumes:
#            - .:/var/www
#        env_file:
#            - .env
#        ports:
#            - "8000:8000"
#        command: php artisan serve --host=0.0.0.0 --port=8000


#    vite:
#        restart: unless-stopped
#        build:
#            context: .
#            target: node_base
#        volumes:
#            - .:/var/www
#        ports:
#            - "5173:5173"
#        command: npm run dev

    mysql:
        container_name: '${PROJECT_ALIAS}_mysql'
        restart: unless-stopped
        image: mysql:8.0.36
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql_data:/var/lib/mysql


    redis:
        container_name: '${PROJECT_ALIAS}_redis'
        image: redis:alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

    meilisearch:
        container_name: '${PROJECT_ALIAS}_meilisearch'
        image: getmeili/meilisearch:latest
        ports:
            - '7700:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - meilisearch_data:/meili_data

    mailpit:
        container_name: '${PROJECT_ALIAS}_mailpit'
        image: 'axllent/mailpit:latest'
        ports:
            - '1025:1025'
            - '8025:8025'

    selenium:
        container_name: '${PROJECT_ALIAS}_selenium'
        image: selenium/standalone-chrome
        extra_hosts:
            - 'host.docker.internal:host-gateway'
#        volumes:
#            - '/dev/shm:/dev/shm'

volumes:
    mysql_data:
    redis_data:
    meilisearch_data:
